### ISSUE TITLE
Implement badge like in other package

### ISSUE THREAD

**Issue by haqqi** [glovory/flutter_eva_color#3]
![image](https://user-images.githubusercontent.com/831763/81933300-57d1c180-9617-11ea-9608-7b67f8e65349.png)

Please do or assign someone to fill up these buttons. One of the example is in flutter_bloc package.

**Comment by haqqi** [comment]
Not all is required. Just several is ok.

**Comment by bunztelan** [comment]
noted

**Comment by bunztelan** [comment]
for now will add two badges, version and license

**Comment by haqqi** [comment]
Ok nice. For now, that's enough.
